name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1.8.0
      with:
        version: "16.0"
    - name: "Set LLVM_SYS_160_PREFIX"
      run: echo "LLVM_SYS_160_PREFIX=$LLVM_PATH" >> $GITHUB_ENV
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
