name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LLVM_SYS_160_PREFIX: /home/runner/work/unnamed/unnamed/llvm
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM
      run: "deb http://apt.llvm.org/lunar/ llvm-toolchain-lunar-16 main"
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
