name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main
        sudo apt-get update
        apt-get install libllvm-16-ocaml-dev libllvm16 llvm-16 llvm-16-dev llvm-16-doc llvm-16-examples llvm-16-runtime

    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
